# Basic placeholders:
#   - %player_name%
#   - %player_ping%
#   - %player_server%
#   - %message%
# LuckPerms placeholders:
#   - %luckperms_prefix%
#   - %luckperms_suffix%
#   - %luckperms_meta_<var>%
format: '(%luckperms_prefix%) %player_name% &7»&r %message%'
