# Basic placeholders:
#   - <player-name>
#   - <player-ping>
#   - <player-server>
#   - %message%
# LuckPerms placeholders:
#   - <luckperms-prefix>
#   - <luckperms-suffix>
#   - <luckperms-meta-<var>>
format: '(<luckperms-prefix>) <player-name> <color:gray>»<reset> <message>'
